#!/bin/bash
testFile=test
if (( $# > 0 )) 
then
	testFile=$1
fi
rm -rf *.out
rm -rf *.in
rm -rf 

flex scanner.lex
bison -d parser.ypp
g++ parser.tab.cpp SymbolTable.cpp bp.cpp output.cpp lex.yy.c

./a.out < $testFile
